M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu22.04.1} date Thu 06 Apr 2023 14:06:32 BST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-06T14:06:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0906
%
G90
G05
T1
X4.3465Y-4.6535
T2
X4.3465Y-2.0236
T3
X5.4094Y-2.126
X5.4094Y-4.5512
T0
M30
